#pragma once

#define JOY_ACTIVE(J)          ( J.active )
#define JOY_ACTIVE_U(J)      ( ( JOY_ACTIVE(J)   >>  0 ) & 1 )
#define JOY_ACTIVE_D(J)      ( ( JOY_ACTIVE(J)   >>  1 ) & 1 )
#define JOY_ACTIVE_L(J)      ( ( JOY_ACTIVE(J)   >>  2 ) & 1 )
#define JOY_ACTIVE_R(J)      ( ( JOY_ACTIVE(J)   >>  3 ) & 1 )
#define JOY_ACTIVE_A(J)      ( ( JOY_ACTIVE(J)   >>  6 ) & 1 )
#define JOY_ACTIVE_B(J)      ( ( JOY_ACTIVE(J)   >>  4 ) & 1 )
#define JOY_ACTIVE_C(J)      ( ( JOY_ACTIVE(J)   >>  5 ) & 1 )
#define JOY_ACTIVE_X(J)      ( ( JOY_ACTIVE(J)   >> 10 ) & 1 )
#define JOY_ACTIVE_Y(J)      ( ( JOY_ACTIVE(J)   >>  9 ) & 1 )
#define JOY_ACTIVE_Z(J)      ( ( JOY_ACTIVE(J)   >>  8 ) & 1 )
#define JOY_ACTIVE_S(J)      ( ( JOY_ACTIVE(J)   >>  7 ) & 1 )
#define JOY_ACTIVE_M(J)      ( ( JOY_ACTIVE(J)   >> 11 ) & 1 )
#define JOY_ACTIVE_V(J)        ( JOY_ACTIVE_U(J)     | JOY_ACTIVE_D(J) )
#define JOY_ACTIVE_H(J)        ( JOY_ACTIVE_L(J)     | JOY_ACTIVE_R(J) )
#define JOY_ACTIVE_DIR(J)      ( JOY_ACTIVE_V(J)     | JOY_ACTIVE_H(J) )
#define JOY_ACTIVE_ABC(J)      ( JOY_ACTIVE_A(J)     | JOY_ACTIVE_B(J)   | JOY_ACTIVE_C(J)   )
#define JOY_ACTIVE_ABCS(J)     ( JOY_ACTIVE_ABC(J)   | JOY_ACTIVE_S(J) )
#define JOY_ACTIVE_XYZ(J)      ( JOY_ACTIVE_X(J)     | JOY_ACTIVE_Y(J)   | JOY_ACTIVE_Z(J)   )
#define JOY_ACTIVE_BTN(J)      ( JOY_ACTIVE_ABC(J)   | JOY_ACTIVE_XYZ(J) )

#define JOY_CHANGED(J)         ( J.changed )
#define JOY_CHANGED_U(J)     ( ( JOY_CHANGED(J)  >>  0 ) & 1 )
#define JOY_CHANGED_D(J)     ( ( JOY_CHANGED(J)  >>  1 ) & 1 )
#define JOY_CHANGED_L(J)     ( ( JOY_CHANGED(J)  >>  2 ) & 1 )
#define JOY_CHANGED_R(J)     ( ( JOY_CHANGED(J)  >>  3 ) & 1 )
#define JOY_CHANGED_A(J)     ( ( JOY_CHANGED(J)  >>  6 ) & 1 )
#define JOY_CHANGED_B(J)     ( ( JOY_CHANGED(J)  >>  4 ) & 1 )
#define JOY_CHANGED_C(J)     ( ( JOY_CHANGED(J)  >>  5 ) & 1 )
#define JOY_CHANGED_X(J)     ( ( JOY_CHANGED(J)  >> 10 ) & 1 )
#define JOY_CHANGED_Y(J)     ( ( JOY_CHANGED(J)  >>  9 ) & 1 )
#define JOY_CHANGED_Z(J)     ( ( JOY_CHANGED(J)  >>  8 ) & 1 )
#define JOY_CHANGED_S(J)     ( ( JOY_CHANGED(J)  >>  7 ) & 1 )
#define JOY_CHANGED_M(J)     ( ( JOY_CHANGED(J)  >> 11 ) & 1 )
#define JOY_CHANGED_V(J)       ( JOY_CHANGED_U(J)    | JOY_CHANGED_D(J) )
#define JOY_CHANGED_H(J)       ( JOY_CHANGED_L(J)    | JOY_CHANGED_R(J) )
#define JOY_CHANGED_DIR(J)     ( JOY_CHANGED_V(J)    | JOY_CHANGED_H(J) )
#define JOY_CHANGED_ABC(J)     ( JOY_CHANGED_A(J)    | JOY_CHANGED_B(J)  | JOY_CHANGED_C(J)  )
#define JOY_CHANGED_ABCS(J)    ( JOY_CHANGED_ABC(J)  | JOY_CHANGED_S(J) )
#define JOY_CHANGED_XYZ(J)     ( JOY_CHANGED_X(J)    | JOY_CHANGED_Y(J)  | JOY_CHANGED_Z(J)  )
#define JOY_CHANGED_BTN(J)     ( JOY_CHANGED_ABC(J)  | JOY_CHANGED_XYZ(J) )

#define JOY_INACTIVE(J)        ( ~JOY_ACTIVE(J) )
#define JOY_INACTIVE_U(J)    ( ( JOY_INACTIVE(J) >>  0 ) & 1 )
#define JOY_INACTIVE_D(J)    ( ( JOY_INACTIVE(J) >>  1 ) & 1 )
#define JOY_INACTIVE_L(J)    ( ( JOY_INACTIVE(J) >>  2 ) & 1 )
#define JOY_INACTIVE_R(J)    ( ( JOY_INACTIVE(J) >>  3 ) & 1 )
#define JOY_INACTIVE_A(J)    ( ( JOY_INACTIVE(J) >>  6 ) & 1 )
#define JOY_INACTIVE_B(J)    ( ( JOY_INACTIVE(J) >>  4 ) & 1 )
#define JOY_INACTIVE_C(J)    ( ( JOY_INACTIVE(J) >>  5 ) & 1 )
#define JOY_INACTIVE_X(J)    ( ( JOY_INACTIVE(J) >> 10 ) & 1 )
#define JOY_INACTIVE_Y(J)    ( ( JOY_INACTIVE(J) >>  9 ) & 1 )
#define JOY_INACTIVE_Z(J)    ( ( JOY_INACTIVE(J) >>  8 ) & 1 )
#define JOY_INACTIVE_S(J)    ( ( JOY_INACTIVE(J) >>  7 ) & 1 )
#define JOY_INACTIVE_M(J)    ( ( JOY_INACTIVE(J) >> 11 ) & 1 )
#define JOY_INACTIVE_V(J)      ( JOY_INACTIVE_U(J)   | JOY_INACTIVE_D(J) )
#define JOY_INACTIVE_H(J)      ( JOY_INACTIVE_L(J)   | JOY_INACTIVE_R(J) )
#define JOY_INACTIVE_DIR(J)    ( JOY_INACTIVE_V(J)   | JOY_INACTIVE_H(J) )
#define JOY_INACTIVE_ABC(J)    ( JOY_INACTIVE_A(J)   | JOY_INACTIVE_B(J) | JOY_INACTIVE_C(J) )
#define JOY_INACTIVE_ABCS(J)   ( JOY_INACTIVE_ABC(J) | JOY_INACTIVE_S(J) )
#define JOY_INACTIVE_XYZ(J)    ( JOY_INACTIVE_X(J)   | JOY_INACTIVE_Y(J) | JOY_INACTIVE_Z(J) )
#define JOY_INACTIVE_BTN(J)    ( JOY_INACTIVE_ABC(J) | JOY_INACTIVE_XYZ(J) )

#define JOY_PRESSED(J)         ( JOY_ACTIVE(J)  & JOY_CHANGED(J) )
#define JOY_PRESSED_U(J)     ( ( JOY_PRESSED(J)  >>  0 ) & 1 )
#define JOY_PRESSED_D(J)     ( ( JOY_PRESSED(J)  >>  1 ) & 1 )
#define JOY_PRESSED_L(J)     ( ( JOY_PRESSED(J)  >>  2 ) & 1 )
#define JOY_PRESSED_R(J)     ( ( JOY_PRESSED(J)  >>  3 ) & 1 )
#define JOY_PRESSED_A(J)     ( ( JOY_PRESSED(J)  >>  6 ) & 1 )
#define JOY_PRESSED_B(J)     ( ( JOY_PRESSED(J)  >>  4 ) & 1 )
#define JOY_PRESSED_C(J)     ( ( JOY_PRESSED(J)  >>  5 ) & 1 )
#define JOY_PRESSED_X(J)     ( ( JOY_PRESSED(J)  >> 10 ) & 1 )
#define JOY_PRESSED_Y(J)     ( ( JOY_PRESSED(J)  >>  9 ) & 1 )
#define JOY_PRESSED_Z(J)     ( ( JOY_PRESSED(J)  >>  8 ) & 1 )
#define JOY_PRESSED_S(J)     ( ( JOY_PRESSED(J)  >>  7 ) & 1 )
#define JOY_PRESSED_M(J)     ( ( JOY_PRESSED(J)  >> 11 ) & 1 )
#define JOY_PRESSED_V(J)       ( JOY_PRESSED_U(J)    | JOY_PRESSED_D(J) )
#define JOY_PRESSED_H(J)       ( JOY_PRESSED_L(J)    | JOY_PRESSED_R(J) )
#define JOY_PRESSED_DIR(J)     ( JOY_PRESSED_V(J)    | JOY_PRESSED_H(J) )
#define JOY_PRESSED_ABC(J)     ( JOY_PRESSED_A(J)    | JOY_PRESSED_B(J)  | JOY_PRESSED_C(J)  )
#define JOY_PRESSED_ABCS(J)    ( JOY_PRESSED_ABC(J)  | JOY_PRESSED_S(J) )
#define JOY_PRESSED_XYZ(J)     ( JOY_PRESSED_X(J)    | JOY_PRESSED_Y(J)  | JOY_PRESSED_Z(J)  )
#define JOY_PRESSED_BTN(J)     ( JOY_PRESSED_ABC(J)  | JOY_PRESSED_XYZ(J) )

#define JOY_RELEASED(J)        ( ~JOY_ACTIVE(J) & JOY_CHANGED(J) )
#define JOY_RELEASED_U(J)    ( ( JOY_RELEASED(J) >>  0 ) & 1 )
#define JOY_RELEASED_D(J)    ( ( JOY_RELEASED(J) >>  1 ) & 1 )
#define JOY_RELEASED_L(J)    ( ( JOY_RELEASED(J) >>  2 ) & 1 )
#define JOY_RELEASED_R(J)    ( ( JOY_RELEASED(J) >>  3 ) & 1 )
#define JOY_RELEASED_A(J)    ( ( JOY_RELEASED(J) >>  6 ) & 1 )
#define JOY_RELEASED_B(J)    ( ( JOY_RELEASED(J) >>  4 ) & 1 )
#define JOY_RELEASED_C(J)    ( ( JOY_RELEASED(J) >>  5 ) & 1 )
#define JOY_RELEASED_X(J)    ( ( JOY_RELEASED(J) >> 10 ) & 1 )
#define JOY_RELEASED_Y(J)    ( ( JOY_RELEASED(J) >>  9 ) & 1 )
#define JOY_RELEASED_Z(J)    ( ( JOY_RELEASED(J) >>  8 ) & 1 )
#define JOY_RELEASED_S(J)    ( ( JOY_RELEASED(J) >>  7 ) & 1 )
#define JOY_RELEASED_M(J)    ( ( JOY_RELEASED(J) >> 11 ) & 1 )
#define JOY_RELEASED_V(J)      ( JOY_RELEASED_U(J)   | JOY_RELEASED_D(J) )
#define JOY_RELEASED_H(J)      ( JOY_RELEASED_L(J)   | JOY_RELEASED_R(J) )
#define JOY_RELEASED_DIR(J)    ( JOY_RELEASED_V(J)   | JOY_RELEASED_H(J) )
#define JOY_RELEASED_ABC(J)    ( JOY_RELEASED_A(J)   | JOY_RELEASED_B(J) | JOY_RELEASED_C(J) )
#define JOY_RELEASED_ABCS(J)   ( JOY_RELEASED_ABC(J) | JOY_RELEASED_S(J) )
#define JOY_RELEASED_XYZ(J)    ( JOY_RELEASED_X(J)   | JOY_RELEASED_Y(J) | JOY_RELEASED_Z(J) )
#define JOY_RELEASED_BTN(J)    ( JOY_RELEASED_ABC(J) | JOY_RELEASED_XYZ(J) )
