#pragma once

#define FRAMELOADER_HELPER_FILE "SGDK/helper.h"

#define FRAMELOADER_INITTIMER_FILE "SGDK/initTimer.c"
#define FRAMELOADER_INITTIMER_FUNCTION SGDK_initTimer

#define FRAMELOADER_SETSPRITE_FILE "SGDK/setSprite.c"
#define FRAMELOADER_SETSPRITE_FUNCTION SGDK_setSprite

#define FRAMELOADER_UPDATE_FILE "SGDK/update.c"
#define FRAMELOADER_UPDATE_FUNCTION SGDK_update