#pragma once

#include "joyreader.h"

joyreader joy1;
joyreader joy2;

enum {
    JOYREADER_UP    = 0,
    JOYREADER_U     = 0,
    JOYREADER_DOWN  = 1,
    JOYREADER_D     = 1,
    JOYREADER_LEFT  = 2,
    JOYREADER_L     = 2,
    JOYREADER_RIGHT = 3,
    JOYREADER_R     = 3,
    JOYREADER_B     = 4,
    JOYREADER_C     = 5,
    JOYREADER_A     = 6,
    JOYREADER_STAR  = 7,
    JOYREADER_S     = 7,
    JOYREADER_Z     = 8,
    JOYREADER_Y     = 9,
    JOYREADER_X     = 10,
    JOYREADER_MODE  = 11,
    JOYREADER_M     = 11,
};


#define joy_active(J)                 ( J.active )
#define joy_active_up(J)            ( ( joy_active(J)   >> JOYREADER_U ) & 1 )
#define joy_active_u(J)             ( ( joy_active(J)   >> JOYREADER_U ) & 1 )
#define joy_active_down(J)          ( ( joy_active(J)   >> JOYREADER_D ) & 1 )
#define joy_active_d(J)             ( ( joy_active(J)   >> JOYREADER_D ) & 1 )
#define joy_active_left(J)          ( ( joy_active(J)   >> JOYREADER_L ) & 1 )
#define joy_active_l(J)             ( ( joy_active(J)   >> JOYREADER_L ) & 1 )
#define joy_active_right(J)         ( ( joy_active(J)   >> JOYREADER_R ) & 1 )
#define joy_active_r(J)             ( ( joy_active(J)   >> JOYREADER_R ) & 1 )
#define joy_active_a(J)             ( ( joy_active(J)   >> JOYREADER_A ) & 1 )
#define joy_active_b(J)             ( ( joy_active(J)   >> JOYREADER_B ) & 1 )
#define joy_active_c(J)             ( ( joy_active(J)   >> JOYREADER_C ) & 1 )
#define joy_active_x(J)             ( ( joy_active(J)   >> JOYREADER_X ) & 1 )
#define joy_active_y(J)             ( ( joy_active(J)   >> JOYREADER_Y ) & 1 )
#define joy_active_z(J)             ( ( joy_active(J)   >> JOYREADER_Z ) & 1 )
#define joy_active_start(J)         ( ( joy_active(J)   >> JOYREADER_S ) & 1 )
#define joy_active_s(J)             ( ( joy_active(J)   >> JOYREADER_S ) & 1 )
#define joy_active_mode(J)          ( ( joy_active(J)   >> JOYREADER_M ) & 1 )
#define joy_active_m(J)             ( ( joy_active(J)   >> JOYREADER_M ) & 1 )
#define joy_active_vertical(J)        ( joy_active_u(J)     | joy_active_d(J) )
#define joy_active_v(J)               ( joy_active_u(J)     | joy_active_d(J) )
#define joy_active_horizontal(J)      ( joy_active_l(J)     | joy_active_r(J) )
#define joy_active_h(J)               ( joy_active_l(J)     | joy_active_r(J) )
#define joy_active_dir(J)             ( joy_active_v(J)     | joy_active_h(J) )
#define joy_active_abc(J)             ( joy_active_a(J)     | joy_active_b(J)   | joy_active_c(J) )
#define joy_active_xyz(J)             ( joy_active_x(J)     | joy_active_y(J)   | joy_active_z(J) )
#define joy_active_btn(J)             ( joy_active_abc(J)   | joy_active_xyz(J) )

#define joy_changed(J)                ( J.changed )
#define joy_changed_up(J)           ( ( joy_changed(J)  >> JOYREADER_U ) & 1 )
#define joy_changed_u(J)            ( ( joy_changed(J)  >> JOYREADER_U ) & 1 )
#define joy_changed_down(J)         ( ( joy_changed(J)  >> JOYREADER_D ) & 1 )
#define joy_changed_d(J)            ( ( joy_changed(J)  >> JOYREADER_D ) & 1 )
#define joy_changed_left(J)         ( ( joy_changed(J)  >> JOYREADER_L ) & 1 )
#define joy_changed_l(J)            ( ( joy_changed(J)  >> JOYREADER_L ) & 1 )
#define joy_changed_right(J)        ( ( joy_changed(J)  >> JOYREADER_R ) & 1 )
#define joy_changed_r(J)            ( ( joy_changed(J)  >> JOYREADER_R ) & 1 )
#define joy_changed_a(J)            ( ( joy_changed(J)  >> JOYREADER_A ) & 1 )
#define joy_changed_b(J)            ( ( joy_changed(J)  >> JOYREADER_B ) & 1 )
#define joy_changed_c(J)            ( ( joy_changed(J)  >> JOYREADER_C ) & 1 )
#define joy_changed_x(J)            ( ( joy_changed(J)  >> JOYREADER_X ) & 1 )
#define joy_changed_y(J)            ( ( joy_changed(J)  >> JOYREADER_Y ) & 1 )
#define joy_changed_z(J)            ( ( joy_changed(J)  >> JOYREADER_Z ) & 1 )
#define joy_changed_start(J)        ( ( joy_changed(J)  >> JOYREADER_S ) & 1 )
#define joy_changed_s(J)            ( ( joy_changed(J)  >> JOYREADER_S ) & 1 )
#define joy_changed_mode(J)         ( ( joy_changed(J)  >> JOYREADER_M ) & 1 )
#define joy_changed_m(J)            ( ( joy_changed(J)  >> JOYREADER_M ) & 1 )
#define joy_changed_vertical(J)       ( joy_changed_u(J)    | joy_changed_d(J) )
#define joy_changed_v(J)              ( joy_changed_u(J)    | joy_changed_d(J) )
#define joy_changed_horizontal(J)     ( joy_changed_l(J)    | joy_changed_r(J) )
#define joy_changed_h(J)              ( joy_changed_l(J)    | joy_changed_r(J) )
#define joy_changed_dir(J)            ( joy_changed_v(J)    | joy_changed_h(J) )
#define joy_changed_abc(J)            ( joy_changed_a(J)    | joy_changed_b(J)  | joy_changed_c(J) )
#define joy_changed_xyz(J)            ( joy_changed_x(J)    | joy_changed_y(J)  | joy_changed_z(J) )
#define joy_changed_btn(J)            ( joy_changed_abc(J)  | joy_changed_xyz(J) )

#define joy_inactive(J)               ( ~joy_active(J) )
#define joy_inactive_up(J)          ( ( joy_inactive(J) >> JOYREADER_U ) & 1 )
#define joy_inactive_u(J)           ( ( joy_inactive(J) >> JOYREADER_U ) & 1 )
#define joy_inactive_down(J)        ( ( joy_inactive(J) >> JOYREADER_D ) & 1 )
#define joy_inactive_d(J)           ( ( joy_inactive(J) >> JOYREADER_D ) & 1 )
#define joy_inactive_left(J)        ( ( joy_inactive(J) >> JOYREADER_L ) & 1 )
#define joy_inactive_l(J)           ( ( joy_inactive(J) >> JOYREADER_L ) & 1 )
#define joy_inactive_right(J)       ( ( joy_inactive(J) >> JOYREADER_R ) & 1 )
#define joy_inactive_r(J)           ( ( joy_inactive(J) >> JOYREADER_R ) & 1 )
#define joy_inactive_a(J)           ( ( joy_inactive(J) >> JOYREADER_A ) & 1 )
#define joy_inactive_b(J)           ( ( joy_inactive(J) >> JOYREADER_B ) & 1 )
#define joy_inactive_c(J)           ( ( joy_inactive(J) >> JOYREADER_C ) & 1 )
#define joy_inactive_x(J)           ( ( joy_inactive(J) >> JOYREADER_X ) & 1 )
#define joy_inactive_y(J)           ( ( joy_inactive(J) >> JOYREADER_Y ) & 1 )
#define joy_inactive_z(J)           ( ( joy_inactive(J) >> JOYREADER_Z ) & 1 )
#define joy_inactive_start(J)       ( ( joy_inactive(J) >> JOYREADER_S ) & 1 )
#define joy_inactive_s(J)           ( ( joy_inactive(J) >> JOYREADER_S ) & 1 )
#define joy_inactive_mode(J)        ( ( joy_inactive(J) >> JOYREADER_M ) & 1 )
#define joy_inactive_m(J)           ( ( joy_inactive(J) >> JOYREADER_M ) & 1 )
#define joy_inactive_vertical(J)      ( joy_inactive_u(J)   | joy_inactive_d(J) )
#define joy_inactive_v(J)             ( joy_inactive_u(J)   | joy_inactive_d(J) )
#define joy_inactive_horizontal(J)    ( joy_inactive_l(J)   | joy_inactive_r(J) )
#define joy_inactive_h(J)             ( joy_inactive_l(J)   | joy_inactive_r(J) )
#define joy_inactive_dir(J)           ( joy_inactive_v(J)   | joy_inactive_h(J) )
#define joy_inactive_abc(J)           ( joy_inactive_a(J)   | joy_inactive_b(J) | joy_inactive_c(J) )
#define joy_inactive_xyz(J)           ( joy_inactive_x(J)   | joy_inactive_y(J) | joy_inactive_z(J) )
#define joy_inactive_btn(J)           ( joy_inactive_abc(J) | joy_inactive_xyz(J) )

#define joy_pressed(J)                ( joy_active(J)  & joy_changed(J) )
#define joy_pressed_up(J)           ( ( joy_pressed(J)  >> JOYREADER_U ) & 1 )
#define joy_pressed_u(J)            ( ( joy_pressed(J)  >> JOYREADER_U ) & 1 )
#define joy_pressed_down(J)         ( ( joy_pressed(J)  >> JOYREADER_D ) & 1 )
#define joy_pressed_d(J)            ( ( joy_pressed(J)  >> JOYREADER_D ) & 1 )
#define joy_pressed_left(J)         ( ( joy_pressed(J)  >> JOYREADER_L ) & 1 )
#define joy_pressed_l(J)            ( ( joy_pressed(J)  >> JOYREADER_L ) & 1 )
#define joy_pressed_right(J)        ( ( joy_pressed(J)  >> JOYREADER_R ) & 1 )
#define joy_pressed_r(J)            ( ( joy_pressed(J)  >> JOYREADER_R ) & 1 )
#define joy_pressed_a(J)            ( ( joy_pressed(J)  >> JOYREADER_A ) & 1 )
#define joy_pressed_b(J)            ( ( joy_pressed(J)  >> JOYREADER_B ) & 1 )
#define joy_pressed_c(J)            ( ( joy_pressed(J)  >> JOYREADER_C ) & 1 )
#define joy_pressed_x(J)            ( ( joy_pressed(J)  >> JOYREADER_X ) & 1 )
#define joy_pressed_y(J)            ( ( joy_pressed(J)  >> JOYREADER_Y ) & 1 )
#define joy_pressed_z(J)            ( ( joy_pressed(J)  >> JOYREADER_Z ) & 1 )
#define joy_pressed_start(J)        ( ( joy_pressed(J)  >> JOYREADER_S ) & 1 )
#define joy_pressed_s(J)            ( ( joy_pressed(J)  >> JOYREADER_S ) & 1 )
#define joy_pressed_mode(J)         ( ( joy_pressed(J)  >> JOYREADER_M ) & 1 )
#define joy_pressed_m(J)            ( ( joy_pressed(J)  >> JOYREADER_M ) & 1 )
#define joy_pressed_vertical(J)       ( joy_pressed_u(J)    | joy_pressed_d(J) )
#define joy_pressed_v(J)              ( joy_pressed_u(J)    | joy_pressed_d(J) )
#define joy_pressed_horizontal(J)     ( joy_pressed_l(J)    | joy_pressed_r(J) )
#define joy_pressed_h(J)              ( joy_pressed_l(J)    | joy_pressed_r(J) )
#define joy_pressed_dir(J)            ( joy_pressed_v(J)    | joy_pressed_h(J) )
#define joy_pressed_abc(J)            ( joy_pressed_a(J)    | joy_pressed_b(J)  | joy_pressed_c(J) )
#define joy_pressed_xyz(J)            ( joy_pressed_x(J)    | joy_pressed_y(J)  | joy_pressed_z(J) )
#define joy_pressed_btn(J)            ( joy_pressed_abc(J)  | joy_pressed_xyz(J) )

#define joy_released(J)               ( ~joy_active(J) & joy_changed(J) )
#define joy_released_up(J)          ( ( joy_released(J) >> JOYREADER_U ) & 1 )
#define joy_released_u(J)           ( ( joy_released(J) >> JOYREADER_U ) & 1 )
#define joy_released_down(J)        ( ( joy_released(J) >> JOYREADER_D ) & 1 )
#define joy_released_d(J)           ( ( joy_released(J) >> JOYREADER_D ) & 1 )
#define joy_released_left(J)        ( ( joy_released(J) >> JOYREADER_L ) & 1 )
#define joy_released_l(J)           ( ( joy_released(J) >> JOYREADER_L ) & 1 )
#define joy_released_right(J)       ( ( joy_released(J) >> JOYREADER_R ) & 1 )
#define joy_released_r(J)           ( ( joy_released(J) >> JOYREADER_R ) & 1 )
#define joy_released_a(J)           ( ( joy_released(J) >> JOYREADER_A ) & 1 )
#define joy_released_b(J)           ( ( joy_released(J) >> JOYREADER_B ) & 1 )
#define joy_released_c(J)           ( ( joy_released(J) >> JOYREADER_C ) & 1 )
#define joy_released_x(J)           ( ( joy_released(J) >> JOYREADER_X ) & 1 )
#define joy_released_y(J)           ( ( joy_released(J) >> JOYREADER_Y ) & 1 )
#define joy_released_z(J)           ( ( joy_released(J) >> JOYREADER_Z ) & 1 )
#define joy_released_start(J)       ( ( joy_released(J) >> JOYREADER_S ) & 1 )
#define joy_released_s(J)           ( ( joy_released(J) >> JOYREADER_S ) & 1 )
#define joy_released_mode(J)        ( ( joy_released(J) >> JOYREADER_M ) & 1 )
#define joy_released_m(J)           ( ( joy_released(J) >> JOYREADER_M ) & 1 )
#define joy_released_vertical(J)      ( joy_released_u(J)   | joy_released_d(J) )
#define joy_released_v(J)             ( joy_released_u(J)   | joy_released_d(J) )
#define joy_released_horizontal(J)    ( joy_released_l(J)   | joy_released_r(J) )
#define joy_released_h(J)             ( joy_released_l(J)   | joy_released_r(J) )
#define joy_released_dir(J)           ( joy_released_v(J)   | joy_released_h(J) )
#define joy_released_abc(J)           ( joy_released_a(J)   | joy_released_b(J) | joy_released_c(J) )
#define joy_released_xyz(J)           ( joy_released_x(J)   | joy_released_y(J) | joy_released_z(J) )
#define joy_released_btn(J)           ( joy_released_abc(J) | joy_released_xyz(J) )



#define joy1_active              joy_active              (joy1)
#define joy1_active_up           joy_active_up           (joy1)
#define joy1_active_u            joy_active_u            (joy1)
#define joy1_active_down         joy_active_down         (joy1)
#define joy1_active_d            joy_active_d            (joy1)
#define joy1_active_left         joy_active_left         (joy1)
#define joy1_active_l            joy_active_l            (joy1)
#define joy1_active_right        joy_active_right        (joy1)
#define joy1_active_r            joy_active_r            (joy1)
#define joy1_active_a            joy_active_a            (joy1)
#define joy1_active_b            joy_active_b            (joy1)
#define joy1_active_c            joy_active_c            (joy1)
#define joy1_active_x            joy_active_x            (joy1)
#define joy1_active_y            joy_active_y            (joy1)
#define joy1_active_z            joy_active_z            (joy1)
#define joy1_active_start        joy_active_start        (joy1)
#define joy1_active_s            joy_active_s            (joy1)
#define joy1_active_mode         joy_active_mode         (joy1)
#define joy1_active_m            joy_active_m            (joy1)
#define joy1_active_vertical     joy_active_vertical     (joy1)
#define joy1_active_v            joy_active_v            (joy1)
#define joy1_active_horizontal   joy_active_horizontal   (joy1)
#define joy1_active_h            joy_active_h            (joy1)
#define joy1_active_dir          joy_active_dir          (joy1)
#define joy1_active_abc          joy_active_abc          (joy1)
#define joy1_active_xyz          joy_active_xyz          (joy1)
#define joy1_active_btn          joy_active_btn          (joy1)

#define joy1_changed             joy_changed             (joy1)
#define joy1_changed_up          joy_changed_up          (joy1)
#define joy1_changed_u           joy_changed_u           (joy1)
#define joy1_changed_down        joy_changed_down        (joy1)
#define joy1_changed_d           joy_changed_d           (joy1)
#define joy1_changed_left        joy_changed_left        (joy1)
#define joy1_changed_l           joy_changed_l           (joy1)
#define joy1_changed_right       joy_changed_right       (joy1)
#define joy1_changed_r           joy_changed_r           (joy1)
#define joy1_changed_a           joy_changed_a           (joy1)
#define joy1_changed_b           joy_changed_b           (joy1)
#define joy1_changed_c           joy_changed_c           (joy1)
#define joy1_changed_x           joy_changed_x           (joy1)
#define joy1_changed_y           joy_changed_y           (joy1)
#define joy1_changed_z           joy_changed_z           (joy1)
#define joy1_changed_start       joy_changed_start       (joy1)
#define joy1_changed_s           joy_changed_s           (joy1)
#define joy1_changed_mode        joy_changed_mode        (joy1)
#define joy1_changed_m           joy_changed_m           (joy1)
#define joy1_changed_vertical    joy_changed_vertical    (joy1)
#define joy1_changed_v           joy_changed_v           (joy1)
#define joy1_changed_horizontal  joy_changed_horizontal  (joy1)
#define joy1_changed_h           joy_changed_h           (joy1)
#define joy1_changed_dir         joy_changed_dir         (joy1)
#define joy1_changed_abc         joy_changed_abc         (joy1)
#define joy1_changed_xyz         joy_changed_xyz         (joy1)
#define joy1_changed_btn         joy_changed_btn         (joy1)

#define joy1_inactive            joy_inactive            (joy1)
#define joy1_inactive_up         joy_inactive_up         (joy1)
#define joy1_inactive_u          joy_inactive_u          (joy1)
#define joy1_inactive_down       joy_inactive_down       (joy1)
#define joy1_inactive_d          joy_inactive_d          (joy1)
#define joy1_inactive_left       joy_inactive_left       (joy1)
#define joy1_inactive_l          joy_inactive_l          (joy1)
#define joy1_inactive_right      joy_inactive_right      (joy1)
#define joy1_inactive_r          joy_inactive_r          (joy1)
#define joy1_inactive_a          joy_inactive_a          (joy1)
#define joy1_inactive_b          joy_inactive_b          (joy1)
#define joy1_inactive_c          joy_inactive_c          (joy1)
#define joy1_inactive_x          joy_inactive_x          (joy1)
#define joy1_inactive_y          joy_inactive_y          (joy1)
#define joy1_inactive_z          joy_inactive_z          (joy1)
#define joy1_inactive_start      joy_inactive_start      (joy1)
#define joy1_inactive_s          joy_inactive_s          (joy1)
#define joy1_inactive_mode       joy_inactive_mode       (joy1)
#define joy1_inactive_m          joy_inactive_m          (joy1)
#define joy1_inactive_vertical   joy_inactive_vertical   (joy1)
#define joy1_inactive_v          joy_inactive_v          (joy1)
#define joy1_inactive_horizontal joy_inactive_horizontal (joy1)
#define joy1_inactive_h          joy_inactive_h          (joy1)
#define joy1_inactive_dir        joy_inactive_dir        (joy1)
#define joy1_inactive_abc        joy_inactive_abc        (joy1)
#define joy1_inactive_xyz        joy_inactive_xyz        (joy1)
#define joy1_inactive_btn        joy_inactive_btn        (joy1)

#define joy1_pressed             joy_pressed             (joy1)
#define joy1_pressed_up          joy_pressed_up          (joy1)
#define joy1_pressed_u           joy_pressed_u           (joy1)
#define joy1_pressed_down        joy_pressed_down        (joy1)
#define joy1_pressed_d           joy_pressed_d           (joy1)
#define joy1_pressed_left        joy_pressed_left        (joy1)
#define joy1_pressed_l           joy_pressed_l           (joy1)
#define joy1_pressed_right       joy_pressed_right       (joy1)
#define joy1_pressed_r           joy_pressed_r           (joy1)
#define joy1_pressed_a           joy_pressed_a           (joy1)
#define joy1_pressed_b           joy_pressed_b           (joy1)
#define joy1_pressed_c           joy_pressed_c           (joy1)
#define joy1_pressed_x           joy_pressed_x           (joy1)
#define joy1_pressed_y           joy_pressed_y           (joy1)
#define joy1_pressed_z           joy_pressed_z           (joy1)
#define joy1_pressed_start       joy_pressed_start       (joy1)
#define joy1_pressed_s           joy_pressed_s           (joy1)
#define joy1_pressed_mode        joy_pressed_mode        (joy1)
#define joy1_pressed_m           joy_pressed_m           (joy1)
#define joy1_pressed_vertical    joy_pressed_vertical    (joy1)
#define joy1_pressed_v           joy_pressed_v           (joy1)
#define joy1_pressed_horizontal  joy_pressed_horizontal  (joy1)
#define joy1_pressed_h           joy_pressed_h           (joy1)
#define joy1_pressed_dir         joy_pressed_dir         (joy1)
#define joy1_pressed_abc         joy_pressed_abc         (joy1)
#define joy1_pressed_xyz         joy_pressed_xyz         (joy1)
#define joy1_pressed_btn         joy_pressed_btn         (joy1)

#define joy1_released            joy_released            (joy1)
#define joy1_released_up         joy_released_up         (joy1)
#define joy1_released_u          joy_released_u          (joy1)
#define joy1_released_down       joy_released_down       (joy1)
#define joy1_released_d          joy_released_d          (joy1)
#define joy1_released_left       joy_released_left       (joy1)
#define joy1_released_l          joy_released_l          (joy1)
#define joy1_released_right      joy_released_right      (joy1)
#define joy1_released_r          joy_released_r          (joy1)
#define joy1_released_a          joy_released_a          (joy1)
#define joy1_released_b          joy_released_b          (joy1)
#define joy1_released_c          joy_released_c          (joy1)
#define joy1_released_x          joy_released_x          (joy1)
#define joy1_released_y          joy_released_y          (joy1)
#define joy1_released_z          joy_released_z          (joy1)
#define joy1_released_start      joy_released_start      (joy1)
#define joy1_released_s          joy_released_s          (joy1)
#define joy1_released_mode       joy_released_mode       (joy1)
#define joy1_released_m          joy_released_m          (joy1)
#define joy1_released_vertical   joy_released_vertical   (joy1)
#define joy1_released_v          joy_released_v          (joy1)
#define joy1_released_horizontal joy_released_horizontal (joy1)
#define joy1_released_h          joy_released_h          (joy1)
#define joy1_released_dir        joy_released_dir        (joy1)
#define joy1_released_abc        joy_released_abc        (joy1)
#define joy1_released_xyz        joy_released_xyz        (joy1)
#define joy1_released_btn        joy_released_btn        (joy1)



#define joy2_active              joy_active              (joy2)
#define joy2_active_up           joy_active_up           (joy2)
#define joy2_active_u            joy_active_u            (joy2)
#define joy2_active_down         joy_active_down         (joy2)
#define joy2_active_d            joy_active_d            (joy2)
#define joy2_active_left         joy_active_left         (joy2)
#define joy2_active_l            joy_active_l            (joy2)
#define joy2_active_right        joy_active_right        (joy2)
#define joy2_active_r            joy_active_r            (joy2)
#define joy2_active_a            joy_active_a            (joy2)
#define joy2_active_b            joy_active_b            (joy2)
#define joy2_active_c            joy_active_c            (joy2)
#define joy2_active_x            joy_active_x            (joy2)
#define joy2_active_y            joy_active_y            (joy2)
#define joy2_active_z            joy_active_z            (joy2)
#define joy2_active_start        joy_active_start        (joy2)
#define joy2_active_s            joy_active_s            (joy2)
#define joy2_active_mode         joy_active_mode         (joy2)
#define joy2_active_m            joy_active_m            (joy2)
#define joy2_active_vertical     joy_active_vertical     (joy2)
#define joy2_active_v            joy_active_v            (joy2)
#define joy2_active_horizontal   joy_active_horizontal   (joy2)
#define joy2_active_h            joy_active_h            (joy2)
#define joy2_active_dir          joy_active_dir          (joy2)
#define joy2_active_abc          joy_active_abc          (joy2)
#define joy2_active_xyz          joy_active_xyz          (joy2)
#define joy2_active_btn          joy_active_btn          (joy2)

#define joy2_changed             joy_changed             (joy2)
#define joy2_changed_up          joy_changed_up          (joy2)
#define joy2_changed_u           joy_changed_u           (joy2)
#define joy2_changed_down        joy_changed_down        (joy2)
#define joy2_changed_d           joy_changed_d           (joy2)
#define joy2_changed_left        joy_changed_left        (joy2)
#define joy2_changed_l           joy_changed_l           (joy2)
#define joy2_changed_right       joy_changed_right       (joy2)
#define joy2_changed_r           joy_changed_r           (joy2)
#define joy2_changed_a           joy_changed_a           (joy2)
#define joy2_changed_b           joy_changed_b           (joy2)
#define joy2_changed_c           joy_changed_c           (joy2)
#define joy2_changed_x           joy_changed_x           (joy2)
#define joy2_changed_y           joy_changed_y           (joy2)
#define joy2_changed_z           joy_changed_z           (joy2)
#define joy2_changed_start       joy_changed_start       (joy2)
#define joy2_changed_s           joy_changed_s           (joy2)
#define joy2_changed_mode        joy_changed_mode        (joy2)
#define joy2_changed_m           joy_changed_m           (joy2)
#define joy2_changed_vertical    joy_changed_vertical    (joy2)
#define joy2_changed_v           joy_changed_v           (joy2)
#define joy2_changed_horizontal  joy_changed_horizontal  (joy2)
#define joy2_changed_h           joy_changed_h           (joy2)
#define joy2_changed_dir         joy_changed_dir         (joy2)
#define joy2_changed_abc         joy_changed_abc         (joy2)
#define joy2_changed_xyz         joy_changed_xyz         (joy2)
#define joy2_changed_btn         joy_changed_btn         (joy2)

#define joy2_inactive            joy_inactive            (joy2)
#define joy2_inactive_up         joy_inactive_up         (joy2)
#define joy2_inactive_u          joy_inactive_u          (joy2)
#define joy2_inactive_down       joy_inactive_down       (joy2)
#define joy2_inactive_d          joy_inactive_d          (joy2)
#define joy2_inactive_left       joy_inactive_left       (joy2)
#define joy2_inactive_l          joy_inactive_l          (joy2)
#define joy2_inactive_right      joy_inactive_right      (joy2)
#define joy2_inactive_r          joy_inactive_r          (joy2)
#define joy2_inactive_a          joy_inactive_a          (joy2)
#define joy2_inactive_b          joy_inactive_b          (joy2)
#define joy2_inactive_c          joy_inactive_c          (joy2)
#define joy2_inactive_x          joy_inactive_x          (joy2)
#define joy2_inactive_y          joy_inactive_y          (joy2)
#define joy2_inactive_z          joy_inactive_z          (joy2)
#define joy2_inactive_start      joy_inactive_start      (joy2)
#define joy2_inactive_s          joy_inactive_s          (joy2)
#define joy2_inactive_mode       joy_inactive_mode       (joy2)
#define joy2_inactive_m          joy_inactive_m          (joy2)
#define joy2_inactive_vertical   joy_inactive_vertical   (joy2)
#define joy2_inactive_v          joy_inactive_v          (joy2)
#define joy2_inactive_horizontal joy_inactive_horizontal (joy2)
#define joy2_inactive_h          joy_inactive_h          (joy2)
#define joy2_inactive_dir        joy_inactive_dir        (joy2)
#define joy2_inactive_abc        joy_inactive_abc        (joy2)
#define joy2_inactive_xyz        joy_inactive_xyz        (joy2)
#define joy2_inactive_btn        joy_inactive_btn        (joy2)

#define joy2_pressed             joy_pressed             (joy2)
#define joy2_pressed_up          joy_pressed_up          (joy2)
#define joy2_pressed_u           joy_pressed_u           (joy2)
#define joy2_pressed_down        joy_pressed_down        (joy2)
#define joy2_pressed_d           joy_pressed_d           (joy2)
#define joy2_pressed_left        joy_pressed_left        (joy2)
#define joy2_pressed_l           joy_pressed_l           (joy2)
#define joy2_pressed_right       joy_pressed_right       (joy2)
#define joy2_pressed_r           joy_pressed_r           (joy2)
#define joy2_pressed_a           joy_pressed_a           (joy2)
#define joy2_pressed_b           joy_pressed_b           (joy2)
#define joy2_pressed_c           joy_pressed_c           (joy2)
#define joy2_pressed_x           joy_pressed_x           (joy2)
#define joy2_pressed_y           joy_pressed_y           (joy2)
#define joy2_pressed_z           joy_pressed_z           (joy2)
#define joy2_pressed_start       joy_pressed_start       (joy2)
#define joy2_pressed_s           joy_pressed_s           (joy2)
#define joy2_pressed_mode        joy_pressed_mode        (joy2)
#define joy2_pressed_m           joy_pressed_m           (joy2)
#define joy2_pressed_vertical    joy_pressed_vertical    (joy2)
#define joy2_pressed_v           joy_pressed_v           (joy2)
#define joy2_pressed_horizontal  joy_pressed_horizontal  (joy2)
#define joy2_pressed_h           joy_pressed_h           (joy2)
#define joy2_pressed_dir         joy_pressed_dir         (joy2)
#define joy2_pressed_abc         joy_pressed_abc         (joy2)
#define joy2_pressed_xyz         joy_pressed_xyz         (joy2)
#define joy2_pressed_btn         joy_pressed_btn         (joy2)

#define joy2_released            joy_released            (joy2)
#define joy2_released_up         joy_released_up         (joy2)
#define joy2_released_u          joy_released_u          (joy2)
#define joy2_released_down       joy_released_down       (joy2)
#define joy2_released_d          joy_released_d          (joy2)
#define joy2_released_left       joy_released_left       (joy2)
#define joy2_released_l          joy_released_l          (joy2)
#define joy2_released_right      joy_released_right      (joy2)
#define joy2_released_r          joy_released_r          (joy2)
#define joy2_released_a          joy_released_a          (joy2)
#define joy2_released_b          joy_released_b          (joy2)
#define joy2_released_c          joy_released_c          (joy2)
#define joy2_released_x          joy_released_x          (joy2)
#define joy2_released_y          joy_released_y          (joy2)
#define joy2_released_z          joy_released_z          (joy2)
#define joy2_released_start      joy_released_start      (joy2)
#define joy2_released_s          joy_released_s          (joy2)
#define joy2_released_mode       joy_released_mode       (joy2)
#define joy2_released_m          joy_released_m          (joy2)
#define joy2_released_vertical   joy_released_vertical   (joy2)
#define joy2_released_v          joy_released_v          (joy2)
#define joy2_released_horizontal joy_released_horizontal (joy2)
#define joy2_released_h          joy_released_h          (joy2)
#define joy2_released_dir        joy_released_dir        (joy2)
#define joy2_released_abc        joy_released_abc        (joy2)
#define joy2_released_xyz        joy_released_xyz        (joy2)
#define joy2_released_btn        joy_released_btn        (joy2)