#pragma once

#include "joyreader.h"

joyreader joy1;
joyreader joy2;


#define JOYREADER_U 0
#define JOYREADER_D 1
#define JOYREADER_L 2
#define JOYREADER_R 3
#define JOYREADER_B 4
#define JOYREADER_C 5
#define JOYREADER_A 6
#define JOYREADER_S 7
#define JOYREADER_Z 8
#define JOYREADER_Y 9
#define JOYREADER_X 10
#define JOYREADER_M 11



#define joy_active(J)         ( J->active )
#define joy_active_u(J)     ( ( joy_active(J)   >> JOYREADER_U ) & 1 )
#define joy_active_d(J)     ( ( joy_active(J)   >> JOYREADER_D ) & 1 )
#define joy_active_l(J)     ( ( joy_active(J)   >> JOYREADER_L ) & 1 )
#define joy_active_r(J)     ( ( joy_active(J)   >> JOYREADER_R ) & 1 )
#define joy_active_a(J)     ( ( joy_active(J)   >> JOYREADER_A ) & 1 )
#define joy_active_b(J)     ( ( joy_active(J)   >> JOYREADER_B ) & 1 )
#define joy_active_c(J)     ( ( joy_active(J)   >> JOYREADER_C ) & 1 )
#define joy_active_x(J)     ( ( joy_active(J)   >> JOYREADER_X ) & 1 )
#define joy_active_y(J)     ( ( joy_active(J)   >> JOYREADER_Y ) & 1 )
#define joy_active_z(J)     ( ( joy_active(J)   >> JOYREADER_Z ) & 1 )
#define joy_active_s(J)     ( ( joy_active(J)   >> JOYREADER_S ) & 1 )
#define joy_active_m(J)     ( ( joy_active(J)   >> JOYREADER_M ) & 1 )
#define joy_active_v(J)       ( joy_active_u(J)     | joy_active_d(J) )
#define joy_active_h(J)       ( joy_active_l(J)     | joy_active_r(J) )
#define joy_active_dir(J)     ( joy_active_v(J)     | joy_active_h(J) )
#define joy_active_abc(J)     ( joy_active_a(J)     | joy_active_b(J)   | joy_active_c(J) )
#define joy_active_xyz(J)     ( joy_active_x(J)     | joy_active_y(J)   | joy_active_z(J) )
#define joy_active_btn(J)     ( joy_active_abc(J)   | joy_active_xyz(J) )

#define joy_changed(J)        ( J->changed )
#define joy_changed_u(J)    ( ( joy_changed(J)  >> JOYREADER_U ) & 1 )
#define joy_changed_d(J)    ( ( joy_changed(J)  >> JOYREADER_D ) & 1 )
#define joy_changed_l(J)    ( ( joy_changed(J)  >> JOYREADER_L ) & 1 )
#define joy_changed_r(J)    ( ( joy_changed(J)  >> JOYREADER_R ) & 1 )
#define joy_changed_a(J)    ( ( joy_changed(J)  >> JOYREADER_A ) & 1 )
#define joy_changed_b(J)    ( ( joy_changed(J)  >> JOYREADER_B ) & 1 )
#define joy_changed_c(J)    ( ( joy_changed(J)  >> JOYREADER_C ) & 1 )
#define joy_changed_x(J)    ( ( joy_changed(J)  >> JOYREADER_X ) & 1 )
#define joy_changed_y(J)    ( ( joy_changed(J)  >> JOYREADER_Y ) & 1 )
#define joy_changed_z(J)    ( ( joy_changed(J)  >> JOYREADER_Z ) & 1 )
#define joy_changed_s(J)    ( ( joy_changed(J)  >> JOYREADER_S ) & 1 )
#define joy_changed_m(J)    ( ( joy_changed(J)  >> JOYREADER_M ) & 1 )
#define joy_changed_v(J)      ( joy_changed_u(J)    | joy_changed_d(J) )
#define joy_changed_h(J)      ( joy_changed_l(J)    | joy_changed_r(J) )
#define joy_changed_dir(J)    ( joy_changed_v(J)    | joy_changed_h(J) )
#define joy_changed_abc(J)    ( joy_changed_a(J)    | joy_changed_b(J)  | joy_changed_c(J) )
#define joy_changed_xyz(J)    ( joy_changed_x(J)    | joy_changed_y(J)  | joy_changed_z(J) )
#define joy_changed_btn(J)    ( joy_changed_abc(J)  | joy_changed_xyz(J) )

#define joy_inactive(J)       ( ~joy_active(J) )
#define joy_inactive_u(J)   ( ( joy_inactive(J) >> JOYREADER_U ) & 1 )
#define joy_inactive_d(J)   ( ( joy_inactive(J) >> JOYREADER_D ) & 1 )
#define joy_inactive_l(J)   ( ( joy_inactive(J) >> JOYREADER_L ) & 1 )
#define joy_inactive_r(J)   ( ( joy_inactive(J) >> JOYREADER_R ) & 1 )
#define joy_inactive_a(J)   ( ( joy_inactive(J) >> JOYREADER_A ) & 1 )
#define joy_inactive_b(J)   ( ( joy_inactive(J) >> JOYREADER_B ) & 1 )
#define joy_inactive_c(J)   ( ( joy_inactive(J) >> JOYREADER_C ) & 1 )
#define joy_inactive_x(J)   ( ( joy_inactive(J) >> JOYREADER_X ) & 1 )
#define joy_inactive_y(J)   ( ( joy_inactive(J) >> JOYREADER_Y ) & 1 )
#define joy_inactive_z(J)   ( ( joy_inactive(J) >> JOYREADER_Z ) & 1 )
#define joy_inactive_s(J)   ( ( joy_inactive(J) >> JOYREADER_S ) & 1 )
#define joy_inactive_m(J)   ( ( joy_inactive(J) >> JOYREADER_M ) & 1 )
#define joy_inactive_v(J)     ( joy_inactive_u(J)   | joy_inactive_d(J) )
#define joy_inactive_h(J)     ( joy_inactive_l(J)   | joy_inactive_r(J) )
#define joy_inactive_dir(J)   ( joy_inactive_v(J)   | joy_inactive_h(J) )
#define joy_inactive_abc(J)   ( joy_inactive_a(J)   | joy_inactive_b(J) | joy_inactive_c(J) )
#define joy_inactive_xyz(J)   ( joy_inactive_x(J)   | joy_inactive_y(J) | joy_inactive_z(J) )
#define joy_inactive_btn(J)   ( joy_inactive_abc(J) | joy_inactive_xyz(J) )

#define joy_pressed(J)        ( joy_active(J)  & joy_changed(J) )
#define joy_pressed_u(J)    ( ( joy_pressed(J)  >> JOYREADER_U ) & 1 )
#define joy_pressed_d(J)    ( ( joy_pressed(J)  >> JOYREADER_D ) & 1 )
#define joy_pressed_l(J)    ( ( joy_pressed(J)  >> JOYREADER_L ) & 1 )
#define joy_pressed_r(J)    ( ( joy_pressed(J)  >> JOYREADER_R ) & 1 )
#define joy_pressed_a(J)    ( ( joy_pressed(J)  >> JOYREADER_A ) & 1 )
#define joy_pressed_b(J)    ( ( joy_pressed(J)  >> JOYREADER_B ) & 1 )
#define joy_pressed_c(J)    ( ( joy_pressed(J)  >> JOYREADER_C ) & 1 )
#define joy_pressed_x(J)    ( ( joy_pressed(J)  >> JOYREADER_X ) & 1 )
#define joy_pressed_y(J)    ( ( joy_pressed(J)  >> JOYREADER_Y ) & 1 )
#define joy_pressed_z(J)    ( ( joy_pressed(J)  >> JOYREADER_Z ) & 1 )
#define joy_pressed_s(J)    ( ( joy_pressed(J)  >> JOYREADER_S ) & 1 )
#define joy_pressed_m(J)    ( ( joy_pressed(J)  >> JOYREADER_M ) & 1 )
#define joy_pressed_v(J)      ( joy_pressed_u(J)    | joy_pressed_d(J) )
#define joy_pressed_h(J)      ( joy_pressed_l(J)    | joy_pressed_r(J) )
#define joy_pressed_dir(J)    ( joy_pressed_v(J)    | joy_pressed_h(J) )
#define joy_pressed_abc(J)    ( joy_pressed_a(J)    | joy_pressed_b(J)  | joy_pressed_c(J) )
#define joy_pressed_xyz(J)    ( joy_pressed_x(J)    | joy_pressed_y(J)  | joy_pressed_z(J) )
#define joy_pressed_btn(J)    ( joy_pressed_abc(J)  | joy_pressed_xyz(J) )

#define joy_released(J)       ( ~joy_active(J) & joy_changed(J) )
#define joy_released_u(J)   ( ( joy_released(J) >> JOYREADER_U ) & 1 )
#define joy_released_d(J)   ( ( joy_released(J) >> JOYREADER_D ) & 1 )
#define joy_released_l(J)   ( ( joy_released(J) >> JOYREADER_L ) & 1 )
#define joy_released_r(J)   ( ( joy_released(J) >> JOYREADER_R ) & 1 )
#define joy_released_a(J)   ( ( joy_released(J) >> JOYREADER_A ) & 1 )
#define joy_released_b(J)   ( ( joy_released(J) >> JOYREADER_B ) & 1 )
#define joy_released_c(J)   ( ( joy_released(J) >> JOYREADER_C ) & 1 )
#define joy_released_x(J)   ( ( joy_released(J) >> JOYREADER_X ) & 1 )
#define joy_released_y(J)   ( ( joy_released(J) >> JOYREADER_Y ) & 1 )
#define joy_released_z(J)   ( ( joy_released(J) >> JOYREADER_Z ) & 1 )
#define joy_released_s(J)   ( ( joy_released(J) >> JOYREADER_S ) & 1 )
#define joy_released_m(J)   ( ( joy_released(J) >> JOYREADER_M ) & 1 )
#define joy_released_v(J)     ( joy_released_u(J)   | joy_released_d(J) )
#define joy_released_h(J)     ( joy_released_l(J)   | joy_released_r(J) )
#define joy_released_dir(J)   ( joy_released_v(J)   | joy_released_h(J) )
#define joy_released_abc(J)   ( joy_released_a(J)   | joy_released_b(J) | joy_released_c(J) )
#define joy_released_xyz(J)   ( joy_released_x(J)   | joy_released_y(J) | joy_released_z(J) )
#define joy_released_btn(J)   ( joy_released_abc(J) | joy_released_xyz(J) )



#define joy1_active       joy_active       (((joyreader *)&joy1))
#define joy1_active_u     joy_active_u     (((joyreader *)&joy1))
#define joy1_active_d     joy_active_d     (((joyreader *)&joy1))
#define joy1_active_l     joy_active_l     (((joyreader *)&joy1))
#define joy1_active_r     joy_active_r     (((joyreader *)&joy1))
#define joy1_active_a     joy_active_a     (((joyreader *)&joy1))
#define joy1_active_b     joy_active_b     (((joyreader *)&joy1))
#define joy1_active_c     joy_active_c     (((joyreader *)&joy1))
#define joy1_active_x     joy_active_x     (((joyreader *)&joy1))
#define joy1_active_y     joy_active_y     (((joyreader *)&joy1))
#define joy1_active_z     joy_active_z     (((joyreader *)&joy1))
#define joy1_active_s     joy_active_s     (((joyreader *)&joy1))
#define joy1_active_m     joy_active_m     (((joyreader *)&joy1))
#define joy1_active_v     joy_active_v     (((joyreader *)&joy1))
#define joy1_active_h     joy_active_h     (((joyreader *)&joy1))
#define joy1_active_dir   joy_active_dir   (((joyreader *)&joy1))
#define joy1_active_abc   joy_active_abc   (((joyreader *)&joy1))
#define joy1_active_xyz   joy_active_xyz   (((joyreader *)&joy1))
#define joy1_active_btn   joy_active_btn   (((joyreader *)&joy1))

#define joy1_changed      joy_changed      (((joyreader *)&joy1))
#define joy1_changed_u    joy_changed_u    (((joyreader *)&joy1))
#define joy1_changed_d    joy_changed_d    (((joyreader *)&joy1))
#define joy1_changed_l    joy_changed_l    (((joyreader *)&joy1))
#define joy1_changed_r    joy_changed_r    (((joyreader *)&joy1))
#define joy1_changed_a    joy_changed_a    (((joyreader *)&joy1))
#define joy1_changed_b    joy_changed_b    (((joyreader *)&joy1))
#define joy1_changed_c    joy_changed_c    (((joyreader *)&joy1))
#define joy1_changed_x    joy_changed_x    (((joyreader *)&joy1))
#define joy1_changed_y    joy_changed_y    (((joyreader *)&joy1))
#define joy1_changed_z    joy_changed_z    (((joyreader *)&joy1))
#define joy1_changed_s    joy_changed_s    (((joyreader *)&joy1))
#define joy1_changed_m    joy_changed_m    (((joyreader *)&joy1))
#define joy1_changed_v    joy_changed_v    (((joyreader *)&joy1))
#define joy1_changed_h    joy_changed_h    (((joyreader *)&joy1))
#define joy1_changed_dir  joy_changed_dir  (((joyreader *)&joy1))
#define joy1_changed_abc  joy_changed_abc  (((joyreader *)&joy1))
#define joy1_changed_xyz  joy_changed_xyz  (((joyreader *)&joy1))
#define joy1_changed_btn  joy_changed_btn  (((joyreader *)&joy1))

#define joy1_inactive     joy_inactive     (((joyreader *)&joy1))
#define joy1_inactive_u   joy_inactive_u   (((joyreader *)&joy1))
#define joy1_inactive_d   joy_inactive_d   (((joyreader *)&joy1))
#define joy1_inactive_l   joy_inactive_l   (((joyreader *)&joy1))
#define joy1_inactive_r   joy_inactive_r   (((joyreader *)&joy1))
#define joy1_inactive_a   joy_inactive_a   (((joyreader *)&joy1))
#define joy1_inactive_b   joy_inactive_b   (((joyreader *)&joy1))
#define joy1_inactive_c   joy_inactive_c   (((joyreader *)&joy1))
#define joy1_inactive_x   joy_inactive_x   (((joyreader *)&joy1))
#define joy1_inactive_y   joy_inactive_y   (((joyreader *)&joy1))
#define joy1_inactive_z   joy_inactive_z   (((joyreader *)&joy1))
#define joy1_inactive_s   joy_inactive_s   (((joyreader *)&joy1))
#define joy1_inactive_m   joy_inactive_m   (((joyreader *)&joy1))
#define joy1_inactive_v   joy_inactive_v   (((joyreader *)&joy1))
#define joy1_inactive_h   joy_inactive_h   (((joyreader *)&joy1))
#define joy1_inactive_dir joy_inactive_dir (((joyreader *)&joy1))
#define joy1_inactive_abc joy_inactive_abc (((joyreader *)&joy1))
#define joy1_inactive_xyz joy_inactive_xyz (((joyreader *)&joy1))
#define joy1_inactive_btn joy_inactive_btn (((joyreader *)&joy1))

#define joy1_pressed      joy_pressed      (((joyreader *)&joy1))
#define joy1_pressed_u    joy_pressed_u    (((joyreader *)&joy1))
#define joy1_pressed_d    joy_pressed_d    (((joyreader *)&joy1))
#define joy1_pressed_l    joy_pressed_l    (((joyreader *)&joy1))
#define joy1_pressed_r    joy_pressed_r    (((joyreader *)&joy1))
#define joy1_pressed_a    joy_pressed_a    (((joyreader *)&joy1))
#define joy1_pressed_b    joy_pressed_b    (((joyreader *)&joy1))
#define joy1_pressed_c    joy_pressed_c    (((joyreader *)&joy1))
#define joy1_pressed_x    joy_pressed_x    (((joyreader *)&joy1))
#define joy1_pressed_y    joy_pressed_y    (((joyreader *)&joy1))
#define joy1_pressed_z    joy_pressed_z    (((joyreader *)&joy1))
#define joy1_pressed_s    joy_pressed_s    (((joyreader *)&joy1))
#define joy1_pressed_m    joy_pressed_m    (((joyreader *)&joy1))
#define joy1_pressed_v    joy_pressed_v    (((joyreader *)&joy1))
#define joy1_pressed_h    joy_pressed_h    (((joyreader *)&joy1))
#define joy1_pressed_dir  joy_pressed_dir  (((joyreader *)&joy1))
#define joy1_pressed_abc  joy_pressed_abc  (((joyreader *)&joy1))
#define joy1_pressed_xyz  joy_pressed_xyz  (((joyreader *)&joy1))
#define joy1_pressed_btn  joy_pressed_btn  (((joyreader *)&joy1))

#define joy1_released     joy_released     (((joyreader *)&joy1))
#define joy1_released_u   joy_released_u   (((joyreader *)&joy1))
#define joy1_released_d   joy_released_d   (((joyreader *)&joy1))
#define joy1_released_l   joy_released_l   (((joyreader *)&joy1))
#define joy1_released_r   joy_released_r   (((joyreader *)&joy1))
#define joy1_released_a   joy_released_a   (((joyreader *)&joy1))
#define joy1_released_b   joy_released_b   (((joyreader *)&joy1))
#define joy1_released_c   joy_released_c   (((joyreader *)&joy1))
#define joy1_released_x   joy_released_x   (((joyreader *)&joy1))
#define joy1_released_y   joy_released_y   (((joyreader *)&joy1))
#define joy1_released_z   joy_released_z   (((joyreader *)&joy1))
#define joy1_released_s   joy_released_s   (((joyreader *)&joy1))
#define joy1_released_m   joy_released_m   (((joyreader *)&joy1))
#define joy1_released_v   joy_released_v   (((joyreader *)&joy1))
#define joy1_released_h   joy_released_h   (((joyreader *)&joy1))
#define joy1_released_dir joy_released_dir (((joyreader *)&joy1))
#define joy1_released_abc joy_released_abc (((joyreader *)&joy1))
#define joy1_released_xyz joy_released_xyz (((joyreader *)&joy1))
#define joy1_released_btn joy_released_btn (((joyreader *)&joy1))



#define joy2_active       joy_active       (((joyreader *)&joy2))
#define joy2_active_u     joy_active_u     (((joyreader *)&joy2))
#define joy2_active_d     joy_active_d     (((joyreader *)&joy2))
#define joy2_active_l     joy_active_l     (((joyreader *)&joy2))
#define joy2_active_r     joy_active_r     (((joyreader *)&joy2))
#define joy2_active_a     joy_active_a     (((joyreader *)&joy2))
#define joy2_active_b     joy_active_b     (((joyreader *)&joy2))
#define joy2_active_c     joy_active_c     (((joyreader *)&joy2))
#define joy2_active_x     joy_active_x     (((joyreader *)&joy2))
#define joy2_active_y     joy_active_y     (((joyreader *)&joy2))
#define joy2_active_z     joy_active_z     (((joyreader *)&joy2))
#define joy2_active_s     joy_active_s     (((joyreader *)&joy2))
#define joy2_active_m     joy_active_m     (((joyreader *)&joy2))
#define joy2_active_v     joy_active_v     (((joyreader *)&joy2))
#define joy2_active_h     joy_active_h     (((joyreader *)&joy2))
#define joy2_active_dir   joy_active_dir   (((joyreader *)&joy2))
#define joy2_active_abc   joy_active_abc   (((joyreader *)&joy2))
#define joy2_active_xyz   joy_active_xyz   (((joyreader *)&joy2))
#define joy2_active_btn   joy_active_btn   (((joyreader *)&joy2))

#define joy2_changed      joy_changed      (((joyreader *)&joy2))
#define joy2_changed_u    joy_changed_u    (((joyreader *)&joy2))
#define joy2_changed_d    joy_changed_d    (((joyreader *)&joy2))
#define joy2_changed_l    joy_changed_l    (((joyreader *)&joy2))
#define joy2_changed_r    joy_changed_r    (((joyreader *)&joy2))
#define joy2_changed_a    joy_changed_a    (((joyreader *)&joy2))
#define joy2_changed_b    joy_changed_b    (((joyreader *)&joy2))
#define joy2_changed_c    joy_changed_c    (((joyreader *)&joy2))
#define joy2_changed_x    joy_changed_x    (((joyreader *)&joy2))
#define joy2_changed_y    joy_changed_y    (((joyreader *)&joy2))
#define joy2_changed_z    joy_changed_z    (((joyreader *)&joy2))
#define joy2_changed_s    joy_changed_s    (((joyreader *)&joy2))
#define joy2_changed_m    joy_changed_m    (((joyreader *)&joy2))
#define joy2_changed_v    joy_changed_v    (((joyreader *)&joy2))
#define joy2_changed_h    joy_changed_h    (((joyreader *)&joy2))
#define joy2_changed_dir  joy_changed_dir  (((joyreader *)&joy2))
#define joy2_changed_abc  joy_changed_abc  (((joyreader *)&joy2))
#define joy2_changed_xyz  joy_changed_xyz  (((joyreader *)&joy2))
#define joy2_changed_btn  joy_changed_btn  (((joyreader *)&joy2))

#define joy2_inactive     joy_inactive     (((joyreader *)&joy2))
#define joy2_inactive_u   joy_inactive_u   (((joyreader *)&joy2))
#define joy2_inactive_d   joy_inactive_d   (((joyreader *)&joy2))
#define joy2_inactive_l   joy_inactive_l   (((joyreader *)&joy2))
#define joy2_inactive_r   joy_inactive_r   (((joyreader *)&joy2))
#define joy2_inactive_a   joy_inactive_a   (((joyreader *)&joy2))
#define joy2_inactive_b   joy_inactive_b   (((joyreader *)&joy2))
#define joy2_inactive_c   joy_inactive_c   (((joyreader *)&joy2))
#define joy2_inactive_x   joy_inactive_x   (((joyreader *)&joy2))
#define joy2_inactive_y   joy_inactive_y   (((joyreader *)&joy2))
#define joy2_inactive_z   joy_inactive_z   (((joyreader *)&joy2))
#define joy2_inactive_s   joy_inactive_s   (((joyreader *)&joy2))
#define joy2_inactive_m   joy_inactive_m   (((joyreader *)&joy2))
#define joy2_inactive_v   joy_inactive_v   (((joyreader *)&joy2))
#define joy2_inactive_h   joy_inactive_h   (((joyreader *)&joy2))
#define joy2_inactive_dir joy_inactive_dir (((joyreader *)&joy2))
#define joy2_inactive_abc joy_inactive_abc (((joyreader *)&joy2))
#define joy2_inactive_xyz joy_inactive_xyz (((joyreader *)&joy2))
#define joy2_inactive_btn joy_inactive_btn (((joyreader *)&joy2))

#define joy2_pressed      joy_pressed      (((joyreader *)&joy2))
#define joy2_pressed_u    joy_pressed_u    (((joyreader *)&joy2))
#define joy2_pressed_d    joy_pressed_d    (((joyreader *)&joy2))
#define joy2_pressed_l    joy_pressed_l    (((joyreader *)&joy2))
#define joy2_pressed_r    joy_pressed_r    (((joyreader *)&joy2))
#define joy2_pressed_a    joy_pressed_a    (((joyreader *)&joy2))
#define joy2_pressed_b    joy_pressed_b    (((joyreader *)&joy2))
#define joy2_pressed_c    joy_pressed_c    (((joyreader *)&joy2))
#define joy2_pressed_x    joy_pressed_x    (((joyreader *)&joy2))
#define joy2_pressed_y    joy_pressed_y    (((joyreader *)&joy2))
#define joy2_pressed_z    joy_pressed_z    (((joyreader *)&joy2))
#define joy2_pressed_s    joy_pressed_s    (((joyreader *)&joy2))
#define joy2_pressed_m    joy_pressed_m    (((joyreader *)&joy2))
#define joy2_pressed_v    joy_pressed_v    (((joyreader *)&joy2))
#define joy2_pressed_h    joy_pressed_h    (((joyreader *)&joy2))
#define joy2_pressed_dir  joy_pressed_dir  (((joyreader *)&joy2))
#define joy2_pressed_abc  joy_pressed_abc  (((joyreader *)&joy2))
#define joy2_pressed_xyz  joy_pressed_xyz  (((joyreader *)&joy2))
#define joy2_pressed_btn  joy_pressed_btn  (((joyreader *)&joy2))

#define joy2_released     joy_released     (((joyreader *)&joy2))
#define joy2_released_u   joy_released_u   (((joyreader *)&joy2))
#define joy2_released_d   joy_released_d   (((joyreader *)&joy2))
#define joy2_released_l   joy_released_l   (((joyreader *)&joy2))
#define joy2_released_r   joy_released_r   (((joyreader *)&joy2))
#define joy2_released_a   joy_released_a   (((joyreader *)&joy2))
#define joy2_released_b   joy_released_b   (((joyreader *)&joy2))
#define joy2_released_c   joy_released_c   (((joyreader *)&joy2))
#define joy2_released_x   joy_released_x   (((joyreader *)&joy2))
#define joy2_released_y   joy_released_y   (((joyreader *)&joy2))
#define joy2_released_z   joy_released_z   (((joyreader *)&joy2))
#define joy2_released_s   joy_released_s   (((joyreader *)&joy2))
#define joy2_released_m   joy_released_m   (((joyreader *)&joy2))
#define joy2_released_v   joy_released_v   (((joyreader *)&joy2))
#define joy2_released_h   joy_released_h   (((joyreader *)&joy2))
#define joy2_released_dir joy_released_dir (((joyreader *)&joy2))
#define joy2_released_abc joy_released_abc (((joyreader *)&joy2))
#define joy2_released_xyz joy_released_xyz (((joyreader *)&joy2))
#define joy2_released_btn joy_released_btn (((joyreader *)&joy2))
